### ISSUE TITLE
It doesn't update blocks when you close the app after its first start

### ISSUE THREAD

**Issue by Libarate** [Snowgem/Snowgem#3]
I am using snowgem-1.0.6a-windowsx64 version. I am strarting the application and it starts synchronizing and updates it upto the lastest block. But if I close the applilcation and run it again, it stucks at the lastest block and doesn't update it up to the lastest block. I need to delete files at C:\Users\Myuser\AppData\Roaming\Snowgem and run the application again. It starts synchronizing from the earliest times and I need to wait about an hour. Please solve this problem.

**Comment by Snowgem** [comment]
Thank you for reporting, please use the latest one here to see what happens: https://snowgem.org/downloads/snowgem-1.0.6b_2-windowsx64.zip

**Comment by versier** [comment]
Also make sure to allow for the wallet software to shutdown fully. I have noticed one occasion where an instance of the snowgem wallet closure window was hanging, even though the application had fully terminated and was not listed as running anywhere. I closed this extra message window via the taskbar, restarted the wallet and have had no issues since.
